= Path Broadcasts (Sample)

Deprecated functionality that uses "broadcasts" to collect extra paths with shell commands.

== DEPRECATION:
. Collection of "extra" path components slow down opening of normal sessions.
. User does not have control of collected path elements.
. Path are collected only when application is started.
  Exceptions are remote actions.
. Applications that run on Android 8.0 (Oreo, API Level 26) or higher no longer receive implicit broadcasts registered in their manifest.
  In transition period "broadcast" functionality will be restricted only to applications signed with the same certificate, i.e. "SecureBox".
. Android 10 (API Level 29) or higher removes execute permission from application home directory.
  So binaries that run on Android 10 (API Level 29) must be installed in write protected location.

== FUTURE:
* Broadcasts based path collection should be replaced with one based on intents send by external applications.
* External application, according to permissions, could send one or more path components, and environment variables.
* "TermOne Plus" will allows user to accept or refuse external application.
* Also "TermOne Plus" will allow user order path components sent.
